services:
  postgres:
    image: postgres:16-alpine
    container_name: dbdesigner-postgres
    environment:
      POSTGRES_USER: dbdesigner
      POSTGRES_PASSWORD: dbdesigner_password
      POSTGRES_DB: dbdesigner
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/drizzle:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbdesigner -d dbdesigner"]
      interval: 3s
      timeout: 2s
      retries: 10
      start_period: 5s
    networks:
      - dbdesigner-network

  server:
    build:
      context: .
      target: server
    container_name: dbdesigner-server
    environment:
      DATABASE_URL: ${DATABASE_URL}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dbdesigner-network

  client:
    build:
      context: .
      target: client
    container_name: dbdesigner-client
    ports:
      - "5173:5173"
    depends_on:
      - server
    networks:
      - dbdesigner-network

volumes:
  postgres_data:
    driver: local

networks:
  dbdesigner-network:
    driver: bridge
