name: Client Biome Check

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  biome-check:
    name: Client Biome Lint & Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
      - name: Build shared package
        run: cd shared && bun run build
        
      - name: Run Biome lint check
        run: cd client && bun run lint
        
      - name: Run Biome format check
        run: cd client && bun run format:check